### PR TITLE
Add Bower Install & Compile To Gulp Develop Call

### PR DESCRIPTION
**Pull request by geenen124**
This should reduce development headaches after new PRs with dependency changes.

### CODE REVIEW

**Comment by bart-de-jonge** [comment]
Looks fine to me

**Comment by Markvanderuit** [comment]
Can you update the readme as well? If bower install etc no longer need to be run manually, please remove them.

**Comment by Markvanderuit** [comment]
Gulp develop no longer working as specified on my machine. Attached example: https://www.dropbox.com/s/d6vi55dhm10y5cw/Screen%20Shot%202016-06-07%20at%2020.10.50.png?dl=0

**Comment by geenen124** [comment]
@Ezlo123 this seems to be an issue with your nodejs permissions. Not with the project. See [NPM Sudo Fix](https://johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/)

**Comment by martijnjanssen** [comment]
Looks good!

**Comment by Markvanderuit** [comment]
Oh, thanks for merging that BEFORE I CAN BLOODY FIX THE ISSUE.

Congratulations, you pissed me off, badly.

**Pull request merged**
